project:
  type: website

website:
  title: "Aj's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ajaverett
      - icon: linkedin
        href: https://www.linkedin.com/in/ajaverett/
      - icon: instagram
        href: https://www.instagram.com/rooftop_asian/
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

